name: The Rust Programming Language
stable: "1.27.0"
stable_date: "2018-06-21"
stable_blog: "https://blog.rust-lang.org/2018/06/21/Rust-1.27.html"
stable_full_version: "rustc 1.27.0 (3eda71b00 2018-06-19)"
beta: "1.28"
beta_date: "2018-08-02"
nightly: "1.29"
channels:
  - name: "stable"
    vers: "1.27.0"
    package: "1.27.0"
  - name: "beta"
    vers: "1.28"
    package: "beta"
  - name: "nightly"
    vers: "1.29"
    package: "nightly"
