name: The Rust Programming Language
stable: "1.31.0"
stable_date: "2018-12-06"
stable_blog: "https://blog.rust-lang.org/2018/12/06/Rust-1.31-and-Rust-2018.html"
stable_full_version: "rustc 1.31.0 (abe02cefd 2018-12-04)"
beta: "1.32"
beta_date: "2019-01-17"
nightly: "1.33"
channels:
  - name: "stable"
    vers: "1.31.0"
    package: "1.31.0"
  - name: "beta"
    vers: "1.32"
    package: "beta"
  - name: "nightly"
    vers: "1.33"
    package: "nightly"
